apiVersion: v1
kind: Service
metadata:
  name: {{ include "country-airport-service-helm.fullname" . }}
  labels:
{{ include "country-airport-service-helm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: service-web
  selector:
    app.kubernetes.io/name: {{ include "country-airport-service-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
