{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "country-airport-service-helm.serviceAccountName" . }}
  labels:
{{ include "country-airport-service-helm.labels" . | indent 4 }}
{{- end -}}
